import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=general-sans@200,201,300,400,401,500,501,600,601,700,701,1,2&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b border-[rgba(84,18,18,0.2)] bg-background/70 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50">
          <div className="container flex items-center justify-between h-16">
            <Link href="/" className="text-lg font-semibold tracking-wide">
              Yori School
            </Link>
            <nav className="flex items-center gap-6 text-sm">
              <Link href="/about" className="hover:underline underline-offset-4">About</Link>
              <Link href="/programs" className="hover:underline underline-offset-4">Programs</Link>
              <Link href="/events" className="hover:underline underline-offset-4">Events</Link>
              <Link href="/news" className="hover:underline underline-offset-4">News</Link>
              <Link href="/admissions" className="hover:underline underline-offset-4">Admissions</Link>
              <Link href="/contact" className="hover:underline underline-offset-4">Contact</Link>
            </nav>
          </div>
        </header>
        <main className="container py-10">
          {children}
        </main>
        <footer className="mt-16 border-t border-[rgba(84,18,18,0.2)] bg-white/60">
          <div className="container py-10 grid gap-8 sm:grid-cols-4 text-sm">
            <div>
              <div className="text-lg font-semibold">Yori School</div>
              <p className="mt-2 opacity-80">A nurturing environment where students thrive.</p>
            </div>
            <div>
              <div className="font-semibold mb-2">Explore</div>
              <ul className="space-y-2">
                <li><Link href="/about" className="hover:underline underline-offset-4">About</Link></li>
                <li><Link href="/programs" className="hover:underline underline-offset-4">Programs</Link></li>
                <li><Link href="/events" className="hover:underline underline-offset-4">Events</Link></li>
                <li><Link href="/news" className="hover:underline underline-offset-4">News</Link></li>
              </ul>
            </div>
            <div>
              <div className="font-semibold mb-2">Admissions</div>
              <ul className="space-y-2">
                <li><Link href="/admissions" className="hover:underline underline-offset-4">How to Apply</Link></li>
                <li><Link href="/contact" className="hover:underline underline-offset-4">Contact Admissions</Link></li>
              </ul>
            </div>
            <div>
              <div className="font-semibold mb-2">Contact</div>
              <ul className="space-y-1 opacity-85">
                <li>info@yorischool.example</li>
                <li>+234 (000) 000-0000</li>
                <li>123 Learning Ave, Lagos</li>
              </ul>
            </div>
          </div>
          <div className="border-t border-[rgba(84,18,18,0.15)]">
            <div className="container py-4 text-xs flex items-center justify-between opacity-80">
              <p>© {new Date().getFullYear()} Yori School. All rights reserved.</p>
              <p>Built with Next.js</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
